### ISSUE TITLE
Roles are not assigned to the default user

### ISSUE THREAD

**Issue by ghermans** [idevelopment/RingMe#100]
- Go to callbacks 
- Click on the info icon.

It will redirect you back to the callbacks list.

**callbackcontroller.php :80**

        if (! $user->is('Agent') || ! $user->is('Manager') || ! $user->is('Administrator')) {
            return redirect()->back();
        }

**Comment by ghermans** [comment]
Same for customers

**Comment by Tjoosten** [comment]
@ghermans what part exact for customers

**Comment by Tjoosten** [comment]
Callback route fixed
