### ISSUE TITLE
Error in view. 

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/RingMe#56]
<img width="590" alt="schermafbeelding 2016-05-20 om 12 06 07" src="https://cloud.githubusercontent.com/assets/5157609/15424526/6a7bc8f4-1e83-11e6-95fb-17e5ec4c39dc.png">

ALign the text with the beginning of the tab. Now there is whitespace.

**Comment by ghermans** [comment]
@Tjoosten can you please verify if the fix is working for you?
