### ISSUE TITLE
Role controller

### ISSUE THREAD

**Issue by Tjoosten** [idevelopment/RingMe#75]
@ghermans can u describe what needs to be done for Settings -> roles in the navbar

**Comment by ghermans** [comment]
## Add roles fields
- name
- permissions

## List roles fields
- name

**Comment by ghermans** [comment]
@Tjoosten i have created the role controller locally, will push it in a couple hours

**Comment by ghermans** [comment]
## Edit view

name
permissions

**Comment by Tjoosten** [comment]
@ghermans can u write the edit, create and specific view for controller.

**Comment by ghermans** [comment]
@Tjoosten working on it right now

**Comment by Tjoosten** [comment]
All right i will put up the tests and controller logic

**Comment by Tjoosten** [comment]
@ghermans closing this one. This issue is specific about the controller. For the views we can create a new issue
